site_name: "DAS Seismology Workshop"
site_url: "https://ai4eps.github.io/DAS_Seismology_Workshop"
site_author: ""
site_description: ""
repo_name: "DAS Seismology Workshop"
repo_url: "https://github.com/AI4EPS/DAS_Seismology_Workshop/"
edit_uri: "edit/main/docs/"

nav:
    - Home: 'README.md'
    - DAS Basics:
      - Slides: 'das_basics.md'
      - 'Lab: DAS Basics': 'notebooks/lab1_das_basics/Notebooks/Basic_DAS_data.ipynb'
    - Deep Learning for DAS:
      - Slides: 'phasenet_das.md'
      - 'Lab 2a: PhaseNet Inference': 'notebooks/lab2_phasenet_das/Notebooks/lab2a_phasenet_das_inference.ipynb'
      - 'Lab 2b: Phase Association': 'notebooks/lab2_phasenet_das/Notebooks/lab2b_phase_association.ipynb'
      - 'Lab 2c: Semi-supervised Training': 'notebooks/lab2_phasenet_das/Notebooks/lab2c_semisupervised_training.ipynb'
      - 'Lab 2d: DASNet Inference': 'notebooks/lab2_phasenet_das/Notebooks/lab2d_dasnet_inference.ipynb'
    - Focal Mechanisms:
      - Slides: 'focal_mechanisms.md'
      - 'dasfm Package': 'notebooks/lab3_focal_mechanisms/Notebooks/dasfm_package.md'
      - 'Lab 3: Download Data': 'notebooks/lab3_focal_mechanisms/Notebooks/lab3_download_data.ipynb'
      - 'Lab 3: Simplest Running': 'notebooks/lab3_focal_mechanisms/Notebooks/lab3_simplest_running.ipynb'
      - 'Lab 3a: Ray Parameters 2D': 'notebooks/lab3_focal_mechanisms/Notebooks/lab3a_ray_parameters_2d.ipynb'
      - 'Lab 3b: DAS Preprocessing': 'notebooks/lab3_focal_mechanisms/Notebooks/lab3b_das_preprocessing.ipynb'
      - 'Lab 3c: Focal Mechanism Inversion': 'notebooks/lab3_focal_mechanisms/Notebooks/lab3c_focal_mechanism_inversion.ipynb'
      - 'Lab 3d: Result Summary': 'notebooks/lab3_focal_mechanisms/Notebooks/lab3d_result_summary.ipynb'
    - Eikonal Tomography:
      - Slides: 'eikonal_tomography.md'
      - 'Lab: 2D Tomography': 'notebooks/lab4_eikonal_tomography/Notebooks/lab4_eikonal_tomography_2d.ipynb'
      - 'Lab: 3D Tomography': 'notebooks/lab4_eikonal_tomography/Notebooks/lab4_eikonal_tomography_3d.ipynb'

theme:
  name: "material"
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - content.code.annotate

plugins:
  - search
  - mkdocs-jupyter:
      ignore_h1_titles: true
      allow_errors: true
      include: ["*.ipynb"]

markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

extra:
  generator: false
  analytics:
    provider: google
    property: G-YB5QD11CE5
