import math
import os
import subprocess
import sys
import unittest

#============================================================================
# UTILITY FUNCTIONS
#
# TODO(donnie):  These will likely migrate to a separate utils.py module
#     as the number of tests grows.
#============================================================================


def get_dir_path(dirname: str, create=False) -> str:
    """
    Given a directory name, uses this module's __file__ attribute to return
    a path to that subdirectory in the same directory as this module.
    """
    dir_path = os.path.join(os.path.dirname(__file__), dirname)

    if not os.path.exists(dir_path):
        if create:
            os.makedirs(dir_path)
        else:
            raise RuntimeError(f'Cannot find directory "{dirname}"')

    return dir_path


def remove_file_if_exists(filepath):
    """
    Remove the specified file if it exists.  If it doesn't exist then this is
    a no-op.
    """
    try:
        os.remove(filepath)
    except FileNotFoundError:
        # This is fine.
        pass


def run_das_db(args: list[str]) -> subprocess.CompletedProcess:
    """
    Run the DAS_db.py script in a separate Python interpreter.
    """
    # Currently since DAS-Utilities isn't a proper Python package, we have to
    # find the path to DAS_db.py from the current module's __file__ attribute.
    # This will get much cleaner in the future.
    path_to_script = os.path.join(os.path.dirname(__file__), '..', '..', 'python', 'DAS_db.py')
    command = [sys.executable, path_to_script]
    command.extend(args)
    # print(f'Arguments to run:  {command}')
    return subprocess.run(command, capture_output=True)


def tokenize_csv_line(line: str) -> list[str]:
    """
    Tokenize a CSV line from the files generated by DAS_db.  These are very
    specific:  Values are separated by spaces, and values containing spaces
    are double-quoted.
    """
    orig_line = line
    # Take off any whitespace
    line = line.strip()

    if '"' in line:
        parts = []
        while len(line) > 0:
            if line[0] == '"':
                i = line.find('"', 1)
                if i == -1:
                    raise RuntimeError(f'Malformed CSV line:  "{orig_line}"')

                parts.append(line[1:i-1])
                line = line[i+1:].lstrip()

            else:
                sp = line.split(maxsplit=1)
                assert len(sp) in (1, 2)

                parts.append(sp[0])
                if len(sp) == 2:
                    line = sp[1].lstrip()
                else:
                    line = ''
    else:
        parts = line.split()

    return parts


def fix_dbrecord_path(rec):
    """
    DAS_db records contain absolute paths to the data files they reference;
    this function turns that path into a path starting with "/dasutil_tests"
    so that we can compare results to an "expected results" file independent
    of the rest of the directory hierarchy.
    """
    path = rec[1]
    i = path.find('dasutil_tests')
    if i != -1:
        path = '/' + path[i:]
    rec[1] = path


def assert_csv_lines_equal(line1, line2):
    assert len(line1) == len(line2), f'Lines don\'t have the same number of columns:  {len(line1)} vs. {len(line2)}'
    assert len(line1) == 11, 'Lines are expected to have 11 columns'

    fix_dbrecord_path(line1)
    fix_dbrecord_path(line2)

    assert line1[0] == line2[0], f'System names don\'t match:  {line1[0]} vs. {line2[0]}'
    assert line1[1] == line2[1], f'Paths don\'t match:  {line1[1]} vs. {line2[1]}'
    assert line1[2] == line2[2], f'Sample-counts don\'t match:  {line1[2]} vs. {line2[2]}'
    assert line1[3] == line2[3], f'Sample-rates don\'t match:  {line1[3]} vs. {line2[3]}'
    assert line1[4] == line2[4], f'Desample values don\'t match:  {line1[4]} vs. {line2[4]}'
    assert line1[5] == line2[5], f'Start-times don\'t match:  {line1[5]} vs. {line2[5]}'
    assert line1[6] == line2[6], f'End-times don\'t match:  {line1[6]} vs. {line2[6]}'
    assert line1[7] == line2[7], f'Number of channels don\'t match:  {line1[7]} vs. {line2[7]}'

    assert math.isclose(float(line1[8]), float(line2[8]), rel_tol=1e-6), \
        f'Channel distances don\'t match:  {line1[8]} vs. {line2[8]}'
    assert math.isclose(float(line1[9]), float(line2[9]), rel_tol=1e-6), \
        f'Channel gauge lengths don\'t match:  {line1[9]} vs. {line2[9]}'

    assert line1[10] == line2[10], f'Start-sample values don\'t match:  {line1[10]} vs. {line2[10]}'


def assert_csv_files_equal(filepath1, filepath2):
    """
    Assert that two DAS_db CSV files are "equal."  Paths in the DB files are
    compared after they have been "fixed" with fix_dbrecord_path().

    Errors are indicated by assertion failures with a message that will
    hopefully help debug issues.
    """
    with open(filepath1) as f1, open(filepath2) as f2:
        f1_lines = f1.readlines()
        f2_lines = f2.readlines()

        # Handle headers first

        # Split headers on whitespace
        f1_header = tokenize_csv_line(f1_lines.pop(0))
        f2_header = tokenize_csv_line(f2_lines.pop(0))

        assert f1_header == f2_header, ('Headers don\'t match.\n' +
            f'f1_header = {f1_header}; f2_header = {f2_header}')

        # For rest of the lines, compare everything except directory paths
        assert len(f1_lines) == len(f2_lines), ('Files have different numbers of lines.\n' +
            f'len(f1_lines) = {len(f1_lines)}; len(f2_lines) = {len(f2_lines)}')

        line_no = 1
        while f1_lines and f2_lines:
            line1 = tokenize_csv_line(f1_lines.pop(0))
            line2 = tokenize_csv_line(f2_lines.pop(0))

            assert_csv_lines_equal(line1, line2)

            # fix_dbrecord_path(line1)
            # fix_dbrecord_path(line2)
            #
            # assert line1 == line2, (f'Line {line_no} in files does not match.\n' +
            #     f'line1 = {line1}; line2 = {line2}')

            line_no += 1


class DAS_db_TestCase(unittest.TestCase):
    """
    Test cases for the DAS_db.py script.
    """

    def test_das_db_noargs_exit_status_2(self):
        """
        Passing no arguments to DAS_db.py should result in an error,
        and an exit status-code of 2.
        """
        proc = run_das_db([])
        self.assertEqual(proc.returncode, 2)

    def test_das_db_nofilesfound_exit_status_1(self):
        """
        If DAS_db.py can't find any files with its file-glob pattern, it
        reports this with an exit status-code of 1.
        """
        data_path = get_dir_path('data')
        testout_path = get_dir_path('testout', create=True)

        glob = f'{data_path}/*.blabla'
        dbfile_path = os.path.join(testout_path, 'nonexistent.txt')

        proc = run_das_db([glob, dbfile_path, 'Nonexistent'])

        self.assertEqual(proc.returncode, 1)

        # Shouldn't create any DB file
        self.assertFalse(os.path.exists(dbfile_path))

    def test_das_db_mammoth_simple_5files(self):
        """
        Run DAS_db.py with a simple set of 5 OptaSense data files from one of
        the Mammoth DAS machines.  The database file should be created by
        this test.
        """
        data_path = get_dir_path('data')
        testout_path = get_dir_path('testout', create=True)
        expected_path = get_dir_path('expected')
        dbfile = 'mammoth.csv'

        glob = f'{data_path}/mammoth-out*.h5'
        dbfile_path = os.path.join(testout_path, dbfile)
        remove_file_if_exists(dbfile_path)

        proc = run_das_db([glob, dbfile_path, 'Mammoth'])

        self.assertEqual(proc.returncode, 0)

        assert_csv_files_equal(os.path.join(testout_path, dbfile),
                               os.path.join(expected_path, dbfile))


    def test_das_db_mammoth_multirun_5files(self):
        """
        Run DAS_db.py multiple times on a set of 5 OptaSense data files
        from one of the Mammoth DAS machines, to build up the database
        file row by row.
        """
        data_path = get_dir_path('data')
        testout_path = get_dir_path('testout', create=True)
        expected_path = get_dir_path('expected')
        dbfile = 'mammoth.csv'

        dbfile_path = os.path.join(testout_path, dbfile)
        remove_file_if_exists(dbfile_path)

        # Add the files in reverse order, so that we can be sure the DAS_db
        # code maintains the order properly.
        for i in range(5, 0, -1):
            glob = f'{data_path}/mammoth-out{i}.h5'
            proc = run_das_db([glob, dbfile_path, 'Mammoth'])
            self.assertEqual(proc.returncode, 0)

            # print('FILE CONTENTS:')
            # with open(dbfile_path) as f:
            #     for line in f:
            #         print(f'FILE:{line}', end='')

        assert_csv_files_equal(os.path.join(testout_path, dbfile),
                               os.path.join(expected_path, dbfile))


    def test_das_db_ridgecrest_simple_6files(self):
        """
        Run DAS_db.py with a simple set of 6 OptaSense data files from one of
        the Ridgecrest DAS machines.  The database file should be created by
        this test.
        """
        data_path = get_dir_path('data')
        testout_path = get_dir_path('testout', create=True)
        expected_path = get_dir_path('expected')
        dbfile = 'ridgecrest.csv'

        glob = f'{data_path}/ridgecrest-out*.h5'
        dbfile_path = os.path.join(testout_path, dbfile)
        remove_file_if_exists(dbfile_path)

        proc = run_das_db([glob, dbfile_path, 'Ridgecrest South'])

        self.assertEqual(proc.returncode, 0)

        assert_csv_files_equal(os.path.join(testout_path, dbfile),
                               os.path.join(expected_path, dbfile))

    def test_das_db_ridgecrest_twice_6files(self):
        """
        Run DAS_db.py twice on a set of 6 OptaSense data files from one of
        the Ridgecrest DAS machines.  The database file should be created
        on the first run, and after the second run should be the same.
        """
        data_path = get_dir_path('data')
        testout_path = get_dir_path('testout', create=True)
        expected_path = get_dir_path('expected')
        dbfile = 'ridgecrest.csv'

        glob = f'{data_path}/ridgecrest-out*.h5'
        dbfile_path = os.path.join(testout_path, dbfile)
        remove_file_if_exists(dbfile_path)

        # Run 1
        proc = run_das_db([glob, dbfile_path, 'Ridgecrest South'])
        self.assertEqual(proc.returncode, 0)

        # Run 2
        proc = run_das_db([glob, dbfile_path, 'Ridgecrest South'])
        self.assertEqual(proc.returncode, 0)

        assert_csv_files_equal(os.path.join(testout_path, dbfile),
                               os.path.join(expected_path, dbfile))

    def test_das_db_ridgecrest_file_with_gap(self):
        """
        Run DAS_db.py with an OptaSense data file that has a gap in the
        samples, from one of the Ridgecrest DAS machines.  The database
        file should be created by this test.
        """
        data_path = get_dir_path('data')
        testout_path = get_dir_path('testout', create=True)
        expected_path = get_dir_path('expected')
        dbfile = 'ridgecrest-gap.csv'

        glob = f'{data_path}/ridgecrest-missingbit.h5'
        dbfile_path = os.path.join(testout_path, dbfile)
        remove_file_if_exists(dbfile_path)

        proc = run_das_db([glob, dbfile_path, 'Ridgecrest South'])

        self.assertEqual(proc.returncode, 0)

        assert_csv_files_equal(os.path.join(testout_path, dbfile),
                               os.path.join(expected_path, dbfile))

